### ISSUE TITLE
Provide CJS build in addition 

### ISSUE THREAD

**Issue by cascornelissen** [wooorm/svg-element-attributes#3]
Hi! 👋🏼 

I'm using this awesome project as a dependency for [svg-spritemap-webpack-plugin](github.com/cascornelissen/svg-spritemap-webpack-plugin). Version 2.0 introduced the ESM build which is great but it also removes the CJS build which in some scenarios (like a Webpack plugin) is still valuable. Webpack plugins can't (really) use ESM, especially `import`,  because that would force all users of the plugin to switch over and the ecosystem isn't quite there yet in my experience.

Therefor I was wondering if it would be possible to publish both the ESM and an additional CJS build to npm?

**Comment by wooorm** [comment]
Hi there!

The plan is to go all in on ESM. Today is the day that Node 10 is EOL. That means all maintained versions of Node support ESM fine.

> Webpack plugins can't (really) use ESM

That’s something webpack *should* definitely support. (I’ve also been hit by it — You could upvote the relevant issues there).

> ecosystem isn't quite there yet in my experience.

I think it’s pretty close, and maintainers actually moving towards ESM will help settle it.

**Comment by cascornelissen** [comment]
I totally agree with you and am sad to see that the way to "solve" this ticket is to make this clear in the docs but it is what it is. Looks like I'm stuck with v1.
